### ISSUE TITLE
Trouble with image...

### ISSUE THREAD

**Issue by PySimpleGUI** [LtqxWYEG/ShitStuckToYourMouse#1]
I gavew it a go and ran into 2 problems.

The first was the import of CREATE_NO_WINDOW which isn't in the 3.6 version I tried on first.

```python
from subprocess import Popen, PIPE, CREATE_NO_WINDOW
```

So, I went with 3.9 and got further.  I tried a number of things to try to get the settings right to find the py.png file that's in the images folder, but I couldn't figure it out.  
![image](https://user-images.githubusercontent.com/46163555/135341676-94c6b023-e56e-424a-8e8a-af73dda749b0.png)

I'm sure I'm missing something stupid that I failed to do but wasn't able to figure it out.... a little help?

```
File "E:\DownloadsE\ShitStuckToYourMouse-main\ShitStuckToYourMouse-main\main.pyw", line 549, in <module>
  main(config)
File "E:\DownloadsE\ShitStuckToYourMouse-main\ShitStuckToYourMouse-main\main.pyw", line 316, in main
  window = make_window('Dark')
File "E:\DownloadsE\ShitStuckToYourMouse-main\ShitStuckToYourMouse-main\main.pyw", line 295, in make_window
  [sg.Image(data = get_img_data(imagePath, first = True), k = 'image')]]
File "E:\DownloadsE\ShitStuckToYourMouse-main\ShitStuckToYourMouse-main\main.pyw", line 171, in get_img_data
  img = Image.open(f)
File "x:\Python\python3.9\Lib\site-packages\PIL\Image.py", line 2904, in open
  fp = builtins.open(filename, "rb")

builtins.FileNotFoundError: [Errno 2] No such file or directory: 'py.png'
```

**Comment by LtqxWYEG** [comment]
Hi, thank you for trying my first project :)

> The first was the import of CREATE_NO_WINDOW which isn't in the 3.6 version I tried on first.
Is that also not available if I'd change it to "import subprocess"? I don't yet know how to respect other Python versions peculiarities.

>  I tried a number of things to try to get the settings right to find the py.png file that's in the images folder, but I couldn't figure it out.
The image in the images folder is not used, but instead the py.png in the root folder. I think I'll delete the images folder here on github. It does not add anything but confusion.
However it should work perfectly fine if you choose a file via the browse button.

On that regard: I changed how the input line works. You can now enter a path and click save/run without crashing the program. It also checks if the file exists now - I totally forgot that. :)

**Comment by PySimpleGUI** [comment]
For small images.... for me that means all images... can be turned into base64 and included in the source code itself which removes the possibility of this problem happening.  May be a technique you can utilize :-)

Your first Issue?  Really?  Ever?  That's SO cool!


```python
py_image = b'iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAZM0lEQVRYCQEoGdfmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAqv8JgNX/Ev///wz/AAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+/gAzM//8Pqqr/CQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+qBgABVvoAAAAAAAAAAAAAAAAAAAAAH6P/GR0KAAkS9gAC9AIA+75bAOoAAAH3AAAAAAAAAAAAAAAAAP+ABgABgPoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AAIAAQD+AAr/GYm+AHgtEwBICgYAJRYVAAEQCQAABwAAAAEAAAD9AAAA8vkAAO3xAADz9wDp3PAAv2dcAHYA1AHjAP8AAwABAP0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AGAAGA+hmU/3CQSQCPIRoAAOfpAAASBQAAAf8A9fz8APb8AAD/AAAAAAMAAAEBAwAEAwEABwYDAAoSFAAAzNwAAIK6AF7XbwGj/445CQFyx/cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKT/DgABAfIAdf8yOxsAedzsAPf18wDNIxEADKPTAPQaDwApFggABvr+APkC/wAB/gAAAAH/APr9AQD5/v4A8gXnAP0cEQAbTzAAkddz/9gAcgHSAKT/DgBcAfIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEg1AEas3wDLNRMA/WE2AE4AAAAAPhn96QOSA7Z8OQBV+/wAAv3/APwBAwD8AP8AAQEBAAAB/wD9/f8A/e/2AOcKBQAMHCQAVAEAAMsAXAH5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwEADQDvAO0tFAAbAAAAAAAAAAAABQMX/ucA1s7oALUdCwAZAgQABAH8AAAIBAACAP8AAQECAP8A/wAA+/0ACPH4ANcKBgALzMz/DzQ0AfEAAP8KAAAB9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADl8gD6LiQAF3PHANlEJwA0BQIAD6jWALsAEwAT//8A+tHsANoDBQD8CAEAAQIBAAEAAwD9BP8AAgEDAPsC/gD93fMA7gwEABioBQD8AAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACV8QD+awAAABcPAAwtFgAn/PwA/1KwALsGBQAB8vYA+XM6ADALBQAG8vcA+fH8APPv9wD5AgAA/wEEAPv8+gD//f4A+/z+APwUBgAM/P0ABenoAAAAAAAAAAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/mCqSlGQRbWwAAAADs/8vLAAv/AAD5YgwAGgYCAB8bEgAFEgsA/fn9AP4NAwADAQMAAgD+AP0MBgDxBvMACvf7AOT5/gD7BQAAAgEDAP8FAQAG/wUA//v+APoAAgD/6QAAAP9tAAd0RgAMMUztBgAAEgBbtHQGAEyN+gEBAPIAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAA/wT/AAEDAQAA+QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7qP9wDwQANQUEAPkFAQACAgEA/gMAAP33AAD6+/sA/f3+ABG4VQBjAAAB+gAAAAAAAAAAAAAAAAAAAAAAAAAAgP8AAoABAP4AAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAA/wAB/gEr/xoAXQBUcTMANyAOABAKBQD//gAA/wkFAPgAAgD5/wEA/vr7AAD8/wAB+/sA//n9AAH1/gAD+/8A8+LxAA/k7wDqCQAABAIGAAQAAAD9/wEA/wb9AAIDBAD/Af0ABwAAAfr/2C3LABBMJgD99OoA/wIIAPrp5gDoqH8BAQC4AAAAAAAAAAAAAAAABAAAAAAAAAAAAP8AA/8BAAIBjv9qRBgAVKFRADwaCAAA9wAAAPn9AAD3/QAA9v0AAPX+AAD1/AAA9vsAAPX7AAD0+gAA9/sAAAn5AAD5+AAADhIA9fv9AKn3/AD4AgMAAgH9AAAA/wD/AQUA/gH7AAQFCgACAAAAAAACDh8AF4AOAADoDgAA/QAAAAQcACEvt//MeXMBNACO/44ACQFyAPcEAAAAAAD/2wcAASX5Uq7/aADaAEVwNQAW8fcAAMPfAOjw+gAG9vwAAvT5AAL4/AD79/4A+vr+APn8+wD2/f8A9f0AAPP8/AD1/P4A9fsAAPb4/AD2/gEA/g0GAAsJ/wADCQsA/wL+AAP4/gD/9P0AAQsBAAIAAAAAAPjR5ADzmxUA+QP0AP3xAQABCQAADBgLAAgyjf+4zqcBSADn//8ACQQA//8GAAEB+XbY/w28yQBTAAgA0MPiACTD5wD/8fkAAPv+APL5+wDs9/wA8fz/APb7AAD2AwAA+wEAAP0A/QD9AgMA/P3+AAAHBQD/AwAAAw8HAAwPBgAECgYAAggBAAMHBQABAAEAAPj8AATuAQD6+P0AAAAA/wEA/hMBAO20/QABFAsA/fgAAP76/gD1C/4AAP8CABUfgQAA4WYAzQAGBACBAAYAAAD6xc8ASvgAAP8bBwAAtOMAwyoPAOP4/QD19/8A8fz8APsHBgACAQEAAgsBAAMKBQAECAkABgj/AAICAgABAQIAAQgBAP8AAQAABQAAAAYEAP4CAQAEDQcAAggEAAT//AD+8gAAAP4IAADp9gADAAAB/wADJgwA++3xAP/4/QD/AwkA//z+APvt9wD69fwAAAZHAAAAAAE0APEEAAAAAAAAAAD1AAAvAf4A8xwMAAsGBAAH7/wA6QgEAAQMAAALBAUAAgMBAP8IBwACDwQABA0IAAIIAQAAA/8ABAcIAPwBAAAAAQAA/wMBAAADBAABCQAAAwkFAAQNBgADAwQABPP3APf5AAD0Av0ADuLrAO0AAAAAAAYTHwAACPYAAgf/AP3//gD/AfwA/f36AAEL+gD/9iP/xWgWATuY6gQAgAH0AAAAAAf3ACABBQD8DwgACggDAAsCAwACAv8A//7/AP38AgD7CgMABBcKAAQQBQAEDgYABQwGAP8FAwD/AP8ABgQBAAABAgABBAAAAAIEAAADAQABA/8AAgMDAP78+wD39f0A8/n9AAUBAQAZvF0AlP+7AGEAFRMFAOz5+gD//wcA/wMDAP7/AQABAwwAAATxAAsIAAAEyTgAAACyBAAAAAD/AAADQQoAHAoAAOoHAgAHAwIAAAD+AP3/AQD9/gMA/w4DAAAUCwAEEgYABQ8HAAMKBQAI/wEADvv+AAT/AAAB+wAAAAD9AP4BAAD/AfsA/v8BAP//AgD+/f8A//v9AP36/QAR9fgAAISpAJ0AAAG8ABUI8wDn3f0AABsHAAICBAAA/wEA//4AAAADAQADBwIAAgEAAPoGNgAAALIEAAAAAAG2/wRK9gAN/AEA6QQBAAEBAAAAAQQA/f7+AAAF/gD/BgUAAwkFAAMEAAAC/P8AGen0AADa5wDUx9cA3/P3APf5/wD9AP0A/wADAP8AAQD/AwMAAP/4AAEAAgAAAgAAAOXlAOoAoQGd/wAABgDUKtwAJYIMAOvd8wDwqQEAABoCAP78/wAAAQAA//8CAP3/AwACAgAAAvcgAAAAAAQAAAAAALAAAwJGAAQEAgAB/v4A/wMAAP0A+wAAAQMA/QEBAP8DAQAB/fsA//UBABrd5gDIl0wAdQAAAe//QAAoADIABwAIAAEA/wABAPwAAAAFAAAA8AD/AP0A/wAAAAAA+QD+ADcAHAB1Q6cAHk9YAA1HAAAAJgAA/oYGAPv4/QABAAEA/gD/AP8AAgD///4A//8BAP4AAAD+AggAAAAABAAAAAD/MzT7UALM+QL/AAICAQD8AQEA/wABAP8BAQD+/QEA//n9APzv+QAf2OYAubBaAXP/1gCbAA83YwAacQEAADUAAAABAAAA/AAAAP4AAAD+AAAA/AAAAPcAAAD+AAAA+QAAAAIAAAALAAD48wAA8t/7APbAAgDvpfoABhoCAP79/gAB/P4A/P8CAAEBAQD/AP8AAgAAAAED+QAAAAAEAAAAAAFnzftPrgDtAAAABgADAPb+AAADAAIA/QEDAP4C/QD9+v8ADPb4AOiwWgFz/+EmswANDEwABHf/APoiAAD72vwAAPf/AP/+AAD+/P8A/vwBAP79AAAA+PwA/gAAAP/6AAD/+v8A/fX/AP36BgAAAQEA88b3AAMRAAD+BQIAAfv+APsAAQAB//4A/wAAAP8BAwABAAAA/gPcAAAAAAQAqv8JAFYB9wEFAOT++QAfBQYA/wQCAAMH/wACAQAA/fIAAPwLBgARnasApv+XAEAAERlMAPcW5QAE5RsA88X8AP/7AQD9/gEA//wAAP/9AQD+/QAA//v+AP37BgD8/QAAAf4AAP3/AAAA/gAA///+AP3w+AD+/v8AAA0DAP76/wD+/gEA//3+AAD/AAD+//8AAP8CAAT/AAAB/b8AAAAABIAVAAOAAAAAB/wA0v0EACkTCAAEEAUABwQEAP/9/gD+DvwA/gIDAAUAmwDRANIAZwAADgAA/fwJAPW/AAD++/0A/wAAAP7+AAD//f4A/v/+AP7//gD+/AAAAAEBAP/+AAD/AQAA/f0AAAABAAD+/gAA/gIBAAIJAQD89wAA//8AAAAHAAACDAAA/fcBAP30+QD+/A4A8AAAATXLwQAAAQAEKusA/QAAAAAMEAC9+vUAXhEFAAoQCgAIDgQAAff9AP719wAA/wUABwAAAPQAAxMXAAcNAAD19foA/ADvAP/9/QAA/wAA/wEAAP4B/QD//wMAAAEEAAAGBQABA/8AAP8CAAD/AAACAgAA//8CAAD+AAAEAf4A/f8BAAQJ/gAACwAABBYBAAYSAgD47P8A9tz7AAnvCADxAsIAAAH//8wADwRWVgH3AAD/Ap1BAdRkt//c/wAAIw8IAOgXBwAO+/4AAOkDAPv6AAAGAAAAAQABBwkABAQAAP0AAgAAAQAAAAIBAP///wD//gEAAAAIAP8GBgABCAIABQgAAP4CAQAABgAAAgT+AP0DAAABAv4A//4AAP4AAQAGAwAA/wgBAAMLAQAFE/4ABA0BAAEK+wD35QgADPQAAPwLeQAAAAAAMwD9BAAAAAAA/wAHAAEA9//zAHv7CQCr8PUAHQQAAPAIBAD/BgIAAv4CAAMAAAAAAP8KBgABAQAAAP78AP/+BQD//gEAAAIBAP4EBwABAgAABRb/AAQYAAABDQQAAAgDAAEHAAAABQAAAQT+AP/+AgAAAf8AAP//AP8BAAAAAP8AAQP9AP78AgD7+gEA+vIGACQBBADV+sMBOsnG/2YABQEBAPQEAAAAAAABAfcA/8wFnQEB3GGw/1sDEwCA9/EAJAMBAAACAQAGAAMADgAAAAkAAwcDAP3+AAD//AAA/gIAAAADAgABBAcA//4AAP3//AAFDQ0ADQwAAAwIAAAABgAAAAIAAAD9AAAAAAIAAAAAAAAAAQAA/AEAAPkAAP38AAD9/AMA/PkAAP3yAAAD4QAA1+3CATrPPwAAAAAAmgAEAAAA+wEAAAAAAAAAAAAAAAAA/8wFAAE0+wAAAAAAv/8IWvUACabVAPzedgASIgEB4f/fR8UAGQ46AOr15AD+AQsA/gMIAAAEBAD/+vsA/fr6AAcIEADnsiYBOADbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAMAuQATAPoABQAKEwAA/AQGAUfp3wAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAA//8JAADc/gABJfkAAAAAAAAAAP8zAAoBzQD2/+NPxQASBToA6fPkAP8DDgABBQcA/wICAP39/gD/9fcA/foMABBL0QD9C/sAAP8JAAAB/gABCQIAAgUAAP/6/AD+AwYA/vIVAR9wGQAAAAAAAAAAAAAAAAAAAAAAAAAA/78AEABBAPkBAAD3AAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAABAfcAAAAAAP//CQAAAAAAwAD/AECgDgABYfYA//z/APz+AAD+/QIAAAICAAL+/wD+/gAAAgH/APoAAgAABPAACv4zAA8KAAAABAAAAAgAAPrpAAD+/QAACCIAAAAiAAAA7gD/ZAAXAJwA6gC8ABIA4QD6AAcAAeRbAPsBAQDwAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQH3AAAAAAAAAAAAv1UAAAAAAAD+BAEABAEAAAUIAwD8AgQA/f4BAPz9/wACAAEAAAEDAPv1AADZmOMAAgcBAAAGCADz1fwAGXADAAosAwDib/kACSEZAA4LAACcAOwBAAD/30MA9SEBAPgAAAAAAFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALCwAAAAAAAP/9BAAHEgAA/gkKAAUGAgD9+wAAAvsAAP/7/wAA+gQAAA0GAAAMAgACAf4A8cT6AB19BQAkghUAAAAAABVS9gDCEu8ACDcRAKUADgBbAO8gAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAAAAA/gbeAAMUNgANIPwA/QoKAP75/wAC//8A+/oDAP35AAAG8AUA+eoAAPv1/gD8+f0ACS8IAAAAAAAAAAD6CREKBgQA+gAJDgABWwDvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA05b1AAAAAAD923sAAP4AAAgHEQAED/QABAz7AAILAAAFEAEACBUBAAYfBAAFHQgABBEFAAs4BADjhvD8+wD//AAAAAbdj+AAHBUQAPAHugAAAAD/vwAQAQEA9wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADG/+MJOgEd9//bVmIAJC+dAAAkAADv9wAA+fv3AAAC/AAB/gAA/P4CAP/5/wD56P4A+ekAAPPQ9wD76f0AAwkXABcKAwDuHdoBNbQnAAAAAOP/AAkdAQD3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADM/wAFNAEA+/+7Ih4AJ1auABweMwABEAAAAAMAAAD+AAAAAAAA/vwAAAL5AAAA8gAAAPYAAPrwAADX5vsABBOCASyThAAAAAD/AAAGAQAA+gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADj/8YJHQE69wAAAAAAAAAA/9hhTwADCkcA/QIuAAMFHQAAAAMA/vztAPv73AAC/cQAEBWuARqF4QAAAAAAAAAA/wAACQEAAPcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//6oJ/9WAEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAG/6pVEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJELlWVMk86AAAAABJRU5ErkJggg=='
```

**Comment by LtqxWYEG** [comment]
> For small images.... for me that means all images... can be turned into base64 and included in the source code itself which removes the possibility of this problem happening. May be a technique you can utilize :-)
> 
> ```python
> py_image = b'AAAAAAAAAAAAAAAAAAAAAAAAAAAA=='
> ```

Ah, I keep that in mind. Thanks!

> Your first Issue? Really? Ever? That's SO cool!

Yea 😁

**Comment by PySimpleGUI** [comment]
We've got some forward progress.......

```
X:\Python\python3.9\python.exe "C:/Python/PycharmProjects/PSG/User Submitted Programs/ShitStuckToYourMouse-main/main.pyw"
Traceback (most recent call last):
  File "C:\Python\PycharmProjects\PSG\User Submitted Programs\ShitStuckToYourMouse-main\main.pyw", line 565, in <module>
    main(config)
  File "C:\Python\PycharmProjects\PSG\User Submitted Programs\ShitStuckToYourMouse-main\main.pyw", line 319, in main
    getVariablesFromConfig(window)
  File "C:\Python\PycharmProjects\PSG\User Submitted Programs\ShitStuckToYourMouse-main\main.pyw", line 97, in getVariablesFromConfig
    window['randomMod'].update(int(config.get("SPARKLES", "randomMod")))
ValueError: invalid literal for int() with base 10: '5.50'

Process finished with exit code 1

```

Longer-term question - I'm wondering if your code could have benefited from using the User Settings and the Exec APIs in PySimpleGUI.  Curious what yo think of them since you're using similar capabilities by calling Popen for example.

**Comment by LtqxWYEG** [comment]
oh that's because you use either the config or default.ini from the release that hasn't been updated. Download the default.ini here and it should work fine.

> EDIT - I think what I should have asked was..... what do you think about using JSON versus Config files. Could be that PySimpleGUI should support both formats.

Hm, I don't like JSON as you can't include comments in it that don't look like values. I chose a config - before the GUI existed - because I wanted to easily have explanations of the values visible to the user. (That was only me though)
I guess now that every explanation is in the GUI, I could change to JSON. I'll take a look at your User Settings solution. Thank you again :)

> Exec APIs in PySimpleGUI

I didn't know that existed. I've had so many issues trying to kill the processes I spawned... no solution worked!! I tried maybe ten different ways and none could kill the processes.
Except the rudimentary and bad "Popen(taskkill...)" which I don't like because it takes so much time. So, yeah, I'll definitely use  your API if it can kill my processes! :)

**Comment by PySimpleGUI** [comment]
>  I tried maybe ten different ways and none could kill the processes.

Oh... uhh..... KILLING a process.... now that would have been a fantastic thing for the Exec APIs to have....

![image](https://user-images.githubusercontent.com/46163555/135531240-456c9310-7607-42db-ab7a-f67f6c3409c5.png)

**Comment by LtqxWYEG** [comment]
> the normal Python subprocessing methods.
> I use psutil to kill prcoesses in a general kind of way.

I tried using subprocess-method with pip and without. (.kill(), .terminate()) Also psutil and all that. I tried getting the process ID with psutil. It just wouldn't work! Googled for hours and went insane

> Oh... uhh..... KILLING a process.... now that would have been a fantastic thing for the Exec APIs to have....

Oh, yea xD (At least for the spawned processes)

**Comment by LtqxWYEG** [comment]
I had to change the name. Getting another perspective on it showed me that it was too vulgar xD

**Comment by PySimpleGUI** [comment]
I think I'm using the straight demo programs from the PySimpleGUI Repo to kill processes:

![image](https://user-images.githubusercontent.com/46163555/135538790-04b052f4-b006-4ca4-a6d1-c4465e9367a3.png)

https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_psutil_Kill_Python_Processes.py
https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_psutil_Kill_Processes.py

I use some version of them to kill all of the running PySimpleGUI programs on my system so I can run batch tests. I think it's able to kill tasks pretty well.  I'm not **sure** of anything though.

**Comment by LtqxWYEG** [comment]
Thank you! I tested it with a compiled exe and it works. I have no idea why and what I may have done wrong using the other methods I tried, but now I'm happy! :)

**Comment by PySimpleGUI** [comment]
FYI - I'm almost done with the first part of the UserSettings support of config files.  The UserSettings object interface is pretty much done.  Next will be the function APIs.

I made the interface for the config files look like this to users:

```python
    settings = sg.UserSettings(r'C:\Python\PycharmProjects\PSG\User Submitted Programs\ShitStuckToYourMouse-main\config.ini', use_config_file=True, autosave=False)
    print(settings['SPARKLES']['randomMod'])
    settings['SPARKLES']['randomMod'] = '**** changed randomMod12343  ****'
    settings['SPARKL']['nbad'] = '+++ NEW VALUE +++'            # Make a new section and value!
    settings.save('config2.ini')
```

It's double indexed

```python
settings[section][key] = value
```

After running the code on your ini file, the new ini  file looks like this:

```
[SPARKLES]
transparentColor = #000000
particleSize = 2
particleAge = 60
ageBrightnessMod = 5.049
ageBrightnessNoise = 12
velocityMod = 0.75
velocityClamp = 200
GRAVITY = 0.0, 0.03
drag = 0.85
FPS = 60
interpolateMouseMovement = True
useOffset = False
offsetX = 20
offsetY = 10
markPosition = False
numParticles = 2
randomMod = **** changed randomMod12343  ****
particleColor = #ff00ff
particleColorRandom = False
ageColor = True
ageColorSpeed = -2.75
ageColorSlope = False
ageColorSlopeConcavity = 0.3
ageColorNoise = 60
ageColorNoiseMod = 0.75
dynamic = True
randomModDynamic = 0.23
printMouseSpeed = False
levelVelocity = 15, 30, 60, 120
levelNumParticles = 5, 8, 14, 20

[OTHeR]
fontColor = None
fontSize = 10
showColor = False
showClock = True
showCPU = True
showRAM = False
showImage = False
imagePath = py.png

[SPARKL]
nbad = +++ NEW VALUE +++
```

**Comment by PySimpleGUI** [comment]
The only problem I'm seeing so far is that comments are stripped.  I've not looked into it further to see if the config parser has a setting for this.  If not, I'll code up whatever it takes to preserve the comments.

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/136696990-2670bd48-0722-47ba-a6c6-0db4b7bfef30.png)

OK, well, this answers if there is an option to not strip comments.

**Comment by PySimpleGUI** [comment]
I add a "preserve comments" option.  I won't be able to preserve the comments on the setting itself, but the single-line comments I will.  It's just code.....
